name: sehi_env
channels:
  - pytorch
  - conda-forge
  - apple
  - defaults
dependencies:
  - altair=5.5.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - archspec=0.2.5=pyhd8ed1ab_0
  - attrs=25.1.0=pyh71513ae_0
  - aws-c-auth=0.7.31=h14f56dd_2
  - aws-c-cal=0.7.4=hd45b2be_2
  - aws-c-common=0.9.29=h7ab814d_0
  - aws-c-compression=0.2.19=hd45b2be_2
  - aws-c-event-stream=0.4.3=hdf5079d_4
  - aws-c-http=0.8.10=h4588aaf_2
  - aws-c-io=0.14.19=h5ad5fc2_1
  - aws-c-mqtt=0.10.7=hbe077eb_2
  - aws-c-s3=0.6.7=h86d2b7d_0
  - aws-c-sdkutils=0.1.19=hd45b2be_4
  - aws-checksums=0.1.20=hd45b2be_1
  - aws-crt-cpp=0.28.3=h4f9f7e0_8
  - aws-sdk-cpp=1.11.407=h880863c_1
  - azure-core-cpp=1.13.0=hd01fc5c_0
  - azure-identity-cpp=1.8.0=h13ea094_2
  - azure-storage-blobs-cpp=12.12.0=hfde595f_0
  - azure-storage-common-cpp=12.7.0=hcf3b6fd_1
  - azure-storage-files-datalake-cpp=12.11.0=h082e32e_1
  - beautifulsoup4=4.13.3=pyha770c72_0
  - blinker=1.9.0=pyhff2d567_0
  - boltons=24.0.0=pyhd8ed1ab_1
  - brotli-python=1.1.0=py310hb4ad77e_2
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.4=h5505292_0
  - ca-certificates=2025.1.31=hf0a4a13_0
  - cachetools=5.5.1=pyhd8ed1ab_0
  - cctools=1010.6=hd01ab73_3
  - cctools_osx-arm64=1010.6=h4bc2523_3
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py310h497396d_0
  - chardet=5.2.0=py310hbe9552e_2
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=25.1.1=py310hbe9552e_0
  - conda-build=25.1.2=py310hbe9552e_0
  - conda-index=0.5.0=pyhd8ed1ab_0
  - conda-libmamba-solver=25.1.1=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - cpp-expected=1.1.0=hffc8910_0
  - cpython=3.10.16=py310hd8ed1ab_1
  - distro=1.9.0=pyhd8ed1ab_1
  - filelock=3.17.0=pyhd8ed1ab_0
  - fmt=11.0.2=h420ef59_0
  - freetype=2.12.1=hadb7bae_2
  - frozendict=2.4.6=py310hf9df320_0
  - fsspec=2025.2.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.1.5=py310h805dbd7_3
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=6.10.0=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py310hbe9552e_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=ha0e7c42_0
  - ld64=951.9=he86490a_3
  - ld64_osx-arm64=951.9=hba2f8ee_3
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20240116.2=cxx17_h00cdb27_1
  - libarchive=3.7.7=h7c07d2a_0
  - libarrow=17.0.0=hc6a7651_16_cpu
  - libarrow-acero=17.0.0=hf9b8971_16_cpu
  - libarrow-dataset=17.0.0=hf9b8971_16_cpu
  - libarrow-substrait=17.0.0=hbf8b706_16_cpu
  - libblas=3.9.0=19_osxarm64_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=19_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.11.1=h73640d1_0
  - libcxx=19.1.7=ha82da77_0
  - libdeflate=1.23=hec38601_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libgoogle-cloud=2.29.0=hfa33a2f_0
  - libgoogle-cloud-storage=2.29.0=h90fd6fa_0
  - libgrpc=1.62.2=h9c18a4f_0
  - libiconv=1.17=h0d3ecfb_2
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=19_osxarm64_openblas
  - liblief=0.14.1=hf9b8971_2
  - libllvm19=19.1.7=hc4b4ae8_1
  - liblzma=5.6.4=h39f12f2_0
  - liblzma-devel=5.6.4=h39f12f2_0
  - libmamba=2.0.5=hdf44a08_1
  - libmambapy=2.0.5=py310h4090bb8_1
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.24=openmp_hd76b1f2_0
  - libparquet=17.0.0=hf0ba9ef_16_cpu
  - libpng=1.6.46=h3783ad8_0
  - libprotobuf=4.25.3=hc39d83c_1
  - libre2-11=2023.09.01=h7b2c953_2
  - libsolv=0.7.30=h6c9b7f8_0
  - libsqlite=3.48.0=h3f77e49_1
  - libssh2=1.11.1=h9cc3647_0
  - libthrift=0.20.0=h64651cc_1
  - libtiff=4.7.0=h551f018_3
  - libutf8proc=2.8.0=hc098a78_1
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.5=h178c5d8_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=15.0.7=h7cfbb63_0
  - llvm-tools=19.1.7=hd2aecb6_1
  - llvm-tools-19=19.1.7=h87a4c7e_1
  - lz4-c=1.9.4=hb7217d7_0
  - lzo=2.10=h93a5062_1001
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py310hc74094e_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - menuinst=2.2.0=py310hbe9552e_0
  - more-itertools=10.6.0=pyhd8ed1ab_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - narwhals=1.25.2=pyhd8ed1ab_0
  - ncurses=6.5=h5e97a16_3
  - networkx=3.2=pyhd8ed1ab_0
  - nlohmann_json=3.11.3=h00cdb27_1
  - numpy=1.24.3=py310haa1e00c_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.4.0=h81ee809_1
  - orc=2.0.2=h75dedd0_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.0.3=py310h1cdf563_1
  - patch=2.7.6=h27ca646_1002
  - pillow=10.4.0=py310h383043f_1
  - pip=23.3.1=pyhd8ed1ab_0
  - pkginfo=1.12.0=pyhd8ed1ab_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - plotly=5.18.0=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - pooch=1.8.2=pyhd8ed1ab_1
  - protobuf=4.25.3=py310ha1b16c5_1
  - psutil=6.1.1=py310h078409c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - py-lief=0.14.1=py310hb4ad77e_2
  - pyarrow=17.0.0=py310h24597f5_2
  - pyarrow-core=17.0.0=py310hc17921c_2_cpu
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py310h078409c_2
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.5.3=pyhd8ed1ab_0
  - pydantic-core=2.14.6=py310hd442715_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.16=h870587a_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-libarchive-c=5.1=py310hbe9552e_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - pytorch=2.3.0=py3.10_0
  - pytz=2025.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310hc74094e_2
  - re2=2023.09.01=h4cba328_2
  - readline=8.2=h92ec313_1
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.5.post0=h5505292_0
  - reproc-cpp=14.2.5.post0=h286801f_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=13.9.4=pyhd8ed1ab_1
  - ripgrep=14.1.1=h0ef69ab_0
  - rpds-py=0.22.3=py310hde4708a_0
  - ruamel.yaml=0.18.10=py310h078409c_0
  - ruamel.yaml.clib=0.2.8=py310hf9df320_1
  - scikit-learn=1.3.0=py310h02d4e2a_0
  - scipy=1.11.1=py310h0975f3d_0
  - setuptools=75.8.0=pyhff2d567_0
  - sigtool=0.1.3=h44b9a77_0
  - simdjson=3.11.6=ha393de7_0
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.2.1=h98b9ce2_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - spdlog=1.15.1=hed1c2b2_0
  - streamlit=1.28.0=pyhd8ed1ab_0
  - sympy=1.13.3=pyh2585a3b_105
  - tapi=1300.6.5=h03f4b80_0
  - tenacity=8.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h5083fa2_1
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchaudio=2.3.0=py310_cpu
  - torchvision=0.18.0=py310_cpu
  - tornado=6.4.2=py310h078409c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - truststore=0.10.0=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h78e105d_0
  - tzlocal=5.2=py310hbe9552e_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - validators=0.34.0=pyhd8ed1ab_1
  - watchdog=6.0.0=py310h078409c_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.6.4=h9a6d368_0
  - xz-gpl-tools=5.6.4=h9a6d368_0
  - xz-tools=5.6.4=h39f12f2_0
  - yaml=0.2.5=h3422bc3_2
  - yaml-cpp=0.8.0=h13dd4ca_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py310h2665a74_1
  - zstd=1.5.6=hb46c0d2_0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/sehi_env
