services:
  - type: web
    name: ecs-sehi-dashboard
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev python3-pyaudio
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run src/dashboard/dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /_stcore/health
    autoDeploy: true
    region: frankfurt
    branch: main 